name: mugen

services:
  postgres:
    image: postgres:16-alpine
    container_name: database
    restart: unless-stopped

    # env_file: .env
    environment:
      POSTGRES_USER:     dev-mugen
      POSTGRES_PASSWORD: dev_mugen
      POSTGRES_DB:       mugen

    ports:
      - "6010:5432"

    volumes:
      - pgdata:$PWD/data
      - ./init-sql:/docker-entrypoint-initdb.d

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev-mugen -d mugen"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8-alpine
    container_name: redis
    restart: unless-stopped
    command: redis-server --save 20 1 --loglevel warning
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  redis-insight:
    image: redis/redisinsight:2.70
    container_name: redis-insight
    restart: unless-stopped
    ports:
      - "5540:5540"
    depends_on:
      - redis
    environment:
      RI_REDIS_HOST: redis
      RI_REDIS_PORT: 6379

# networks:
#   - internal

volumes:
  pgdata:
  redisdata:

# networks:
#   internal: