version: "3.9"

name: mugen

services:
  postgres:
    image: postgres:16-alpine
    container_name: database
    restart: unless-stopped

    # env_file: .env
    environment:
      POSTGRES_USER:     dev-mugen
      POSTGRES_PASSWORD: dev_mugen
      POSTGRES_DB:       mugen

    ports:
      - "6010:5432"

    volumes:
      - pgdata:$PWD/data
      - ./init-sql:/docker-entrypoint-initdb.d

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev-mugen -d mugen"]
      interval: 10s
      timeout: 5s
      retries: 5

    # networks:
    #   - internal

volumes:
  pgdata:

# networks:
#   internal: